routes/web.php
<?php

use App\Symptom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang', 'PageController@locale')->name('locale');
Route::get('lang/{locale}', 'PageController@setLocale');

// Pages
Route::get('', 'PageController@survey')->name('survey');
Route::post('', 'ReportController@store')->name('survey.store');
Route::get('thank-you', 'PageController@thanks')->name('thanks');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('map', 'PageController@map')->name('map');
Route::get('privacy', 'PageController@privacy')->name('privacy');
Route::get('about-us', 'PageController@aboutUs')->name('about-us');

// Biñan
Route::get('biñan', 'PageController@biñan')->name('biñan');
Route::get('binan', 'RedirectController@biñan');

// Auth
Auth::routes(['register' => false]);
Route::get('password/{token}', 'PasswordController@createPassword')->name('password-create');
Route::post('password/create', 'PasswordController@storePassword')->name('password-store');
// Route::get('verify/{token}', 'AdminController@verifyEmail');

Route::prefix('admin')->name('admin.')->group(function () {

    // Main admin page
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('map', 'AdminPageController@map')->name('map');

    Route::get('cases', 'AdminPageController@cases')->name('cases');

    // Resources
    Route::get('reports/problems', 'ReportController@problems')->name('reports.problems');
    Route::resource('reports', 'ReportController');
    Route::post('reports/{report}/flag', 'ReportController@flag')->name('reports.flag');
    Route::post('reports/{report}/fake', 'ReportController@fake')->name('reports.fake');
    Route::post('reports/{report}/unflag', 'ReportController@unflag')->name('reports.unflag');
    Route::post('reports/{report}/unfake', 'ReportController@unfake')->name('reports.unfake');
    Route::resource('users', 'UserController');

    Route::resource('symptoms', 'SymptomController');
    Route::get('symptoms/{symptom}/image/edit', 'SymptomController@imageEdit')->name('symptoms.image.edit');
    Route::put('symptoms/{symptom}/image/update', 'SymptomController@imageUpdate')->name('symptoms.image.update');
    Route::post('symptoms/image/none/update', 'SymptomController@noneImageUpdate')->name('symptoms.image.none.update');

    Route::resource('case-statuses', 'CaseStatusController');
    Route::put('case-statuses/{case_status}/activate', 'CaseStatusController@activate')->name('case-statuses.activate');
    Route::put('case-statuses/{case_status}/deactivate', 'CaseStatusController@deactivate')->name('case-statuses.deactivate');

    Route::resource('regions', 'RegionController');
    Route::resource('provinces', 'ProvinceController');
    Route::resource('cities', 'CityController');
    Route::resource('barangays', 'BarangayController');
    Route::resource('barangay-cases', 'BarangayCaseController');

    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/password/update', 'ProfileController@updatePassword')->name('profile.password.update');
});

Route::get('{url}', function (string $url) {
    return redirect(route('survey'));
});

resources/views/admin/case-statuses/edit.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
      )))
      @slot('current_page', 'Case Statuses')
    @endcomponent

    <card-basic title="Edit Case Status" class="mt-4">
      @include('components.errors')
      <form action="{{ route('admin.case-statuses.update', ['case_status' => $caseStatus->id]) }}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
          <label for="inputName">Case Status</label>
          <input type="text" class="form-control" id="inputName" name="name" value="{{ $caseStatus->name }}" required>
        </div>
        <button-submit class="float-right"/>
      </form>
    </card-basic>

  </div>
@endsection

resources/views/admin/case-statuses/index.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
      )))
      @slot('current_page', 'Case Statuses')
    @endcomponent

    <card-basic title="Add Case Status" class="mt-4">
      @include('components.errors')
      <form action="{{ route('admin.case-statuses.store') }}" method="POST">
        @csrf
        <div class="form-group">
          <label for="inputName">Case Status</label>
          <input type="text" class="form-control" id="inputName" name="name">
        </div>
        <button-submit class="float-right"/>
      </form>
    </card-basic>

    <card-basic title="Case Statuses" class="mt-4">
      <template v-slot:image>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <td>Name</td>
                <td>Created</td>
                <td>Status</td>
                <td></td>
              </tr>
            </thead>
            <tbody>
              @foreach($caseStatuses as $caseStatus)
              <tr>
                <td>
                  {{ $caseStatus->name }}
                </td>
                <td>
                  {{ $caseStatus->created_at ? $caseStatus->created_at->diffForHumans() : '' }}
                </td>
                <td>
                  @if(isset($caseStatus->deactivated_at))
                    <span class="badge badge-warning">Deactivated</span>
                  @endif
                </td>
                <td>
                  <options-dropdown icon="more_horiz">
                    <a class="dropdown-item" href="{{ route('admin.case-statuses.edit', ['case_status' => $caseStatus->id]) }}">
                      Edit
                    </a>
                    @if(isset($caseStatus->deactivated_at))
                      <button class="dropdown-item text-success" data-toggle="modal" data-target="#confirmationModal"
                        data-action="{{ route('admin.case-statuses.activate', ['case_status' => $caseStatus->id]) }}"
                        data-method="PUT">
                        Activate
                      </button>
                    @else
                      <button class="dropdown-item text-danger" data-toggle="modal" data-target="#confirmationModal"
                        data-action="{{ route('admin.case-statuses.deactivate', ['case_status' => $caseStatus->id]) }}"
                        data-method="PUT">
                        Deactivate
                      </button>
                    @endif
                    <button class="dropdown-item text-danger" data-toggle="modal" data-target="#deleteConfirmationModal"
                      data-action="{{ route('admin.case-statuses.destroy', ['case_status' => $caseStatus->id]) }}">
                      Delete
                    </button>
                  </options-dropdown>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </tr>
      </template>
    </card-basic>

  </div>
@endsection