routes/web.php
<?php

use App\Symptom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang', 'PageController@locale')->name('locale');
Route::get('lang/{locale}', 'PageController@setLocale');

// Pages
Route::get('', 'PageController@survey')->name('survey');
Route::post('', 'ReportController@store')->name('survey.store');
Route::get('thank-you', 'PageController@thanks')->name('thanks');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('map', 'PageController@map')->name('map');
Route::get('privacy', 'PageController@privacy')->name('privacy');
Route::get('about-us', 'PageController@aboutUs')->name('about-us');

// Biñan
Route::get('biñan', 'PageController@biñan')->name('biñan');
Route::get('binan', 'RedirectController@biñan');

// Auth
Auth::routes(['register' => false]);
Route::get('password/{token}', 'PasswordController@createPassword')->name('password-create');
Route::post('password/create', 'PasswordController@storePassword')->name('password-store');
// Route::get('verify/{token}', 'AdminController@verifyEmail');

Route::prefix('admin')->name('admin.')->group(function () {

    // Main admin page
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('map', 'AdminPageController@map')->name('map');

    Route::get('cases', 'AdminPageController@cases')->name('cases');

    // Resources
    Route::get('reports/problems', 'ReportController@problems')->name('reports.problems');
    Route::resource('reports', 'ReportController');
    Route::post('reports/{report}/flag', 'ReportController@flag')->name('reports.flag');
    Route::post('reports/{report}/fake', 'ReportController@fake')->name('reports.fake');
    Route::post('reports/{report}/unflag', 'ReportController@unflag')->name('reports.unflag');
    Route::post('reports/{report}/unfake', 'ReportController@unfake')->name('reports.unfake');
    Route::resource('users', 'UserController');

    Route::resource('symptoms', 'SymptomController');
    Route::get('symptoms/{symptom}/image/edit', 'SymptomController@imageEdit')->name('symptoms.image.edit');
    Route::put('symptoms/{symptom}/image/update', 'SymptomController@imageUpdate')->name('symptoms.image.update');
    Route::post('symptoms/image/none/update', 'SymptomController@noneImageUpdate')->name('symptoms.image.none.update');

    Route::resource('case-statuses', 'CaseStatusController');
    Route::put('case-statuses/{case_status}/activate', 'CaseStatusController@activate')->name('case-statuses.activate');
    Route::put('case-statuses/{case_status}/deactivate', 'CaseStatusController@deactivate')->name('case-statuses.deactivate');

    Route::resource('regions', 'RegionController');
    Route::resource('provinces', 'ProvinceController');
    Route::resource('cities', 'CityController');
    Route::resource('barangays', 'BarangayController');
    Route::resource('barangay-cases', 'BarangayCaseController');

    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/password/update', 'ProfileController@updatePassword')->name('profile.password.update');
});

Route::get('{url}', function (string $url) {
    return redirect(route('survey'));
});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('current_page', 'Dashboard')
    @endcomponent

    <card-basic title="Admin Dashboard" class="mt-4">
      <p>
        Hi {{ Auth::user()->name }}!. You're logged in!
      </p>
      <p class="m-0">
        <a class="btn btn-primary btn-raised m-1" href="{{ route('admin.map') }}">
          Admin Map
        </a>
        <a class="btn btn-primary btn-raised m-1" href="{{ route('admin.cities.index') }}">
          Cities
        </a>
        <a class="btn btn-primary btn-raised m-1" href="{{ route('admin.barangays.index') }}">
          Barangays
        </a>
        <a class="btn btn-primary btn-raised m-1" href="{{ route('admin.cases') }}">
          Cases
        </a>
      </p>
      <template v-slot:footer>
        <a class="btn btn-primary btn-raised float-right m-1" href="{{ route('logout') }}"
          onclick="event.preventDefault();document.getElementById('logout-button').submit();">
          Logout
        </a>
        <form id="logout-button" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        </form>
        <a class="btn btn-primary btn-raised float-right m-1" href="{{ route('map') }}" target="_blank">Map</a>
        <a class="btn btn-primary btn-raised float-right m-1" href="{{ route('survey') }}" target="_blank">Survey</a>
      </template>
    </card-basic>

    <card-basic title="Statistics" class="mt-4">
      <h4>
        Reports Last Hour:
        <span class="badge badge-secondary">
          {{ $allReports->where('created_at', '>', Carbon\Carbon::now()->subHour())->count() }}
        </span>
      </h4>
      <h4>
        Reports Last 24 Hours:
        <span class="badge badge-secondary">
          {{ $allReports->where('created_at', '>', Carbon\Carbon::now()->subDay())->count() }}
        </span>
      </h4>
      <h4>
        Reports Last 7 Days:
        <span class="badge badge-secondary">
          {{ $allReports->where('created_at', '>', Carbon\Carbon::now()->subWeek())->count() }}
        </span>
      </h4>
      <h4>
        Reports Last Month:
        <span class="badge badge-secondary">
          {{ $allReports->where('created_at', '>', Carbon\Carbon::now()->subWeek())->count() }}
        </span>
      </h4>
      <h4>
        Total Reports:
        <span class="badge badge-secondary">
          {{ $allReports->count() }}
        </span>
      </h4>
    </card-basic>

    @component('components.cards.reports')
      @slot('reports', $reports)
    @endcomponent

    @component('components.cards.users')
      @slot('users', $users)
    @endcomponent

  </div>
@endsection

resources/views/admin/map.blade.php
@extends('layouts.admin.index')

@section('styles')
@endsection

@section('content')
  <div class="container-fluid">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
      )))
      @slot('current_page', 'Map')
    @endcomponent

    <div class="row">

      <div class="col-md-8">
        <card-basic title="Reports" class="mt-4">
          <template v-slot:image>
            <div id="map" class="w-100" style="height: 512px;"></div>
          </template>
        </card-basic>
      </div>

      <div class="col-md-4">

        <card-basic title="Filter" class="mt-4 border-0 rounded shadow">

          @foreach(App\Symptom::all() as $symptom)
            <div class="custom-control custom-switch mt-2">
              <input
                id="symptomSwitch{{ $symptom->id }}"
                class="custom-control-input"
                type="checkbox"
                onchange="symptomSwitch(this.checked, {{ $symptom->id }})" checked>
              <label class="custom-control-label" for="symptomSwitch{{ $symptom->id }}">
                @if($symptom->name == 'Fever')
                  <img src="https://chart.apis.google.com/chart?cht=d&chdp=mapsapi&chl=pin%27i%5Chv%27a%5C]h%5C]o%5Cf44336%27fC%5CLauto%27f%5C&ext=.png" class="img-fluid" alt="Red Pin">
                @else
                  <img src="https://chart.apis.google.com/chart?cht=d&chdp=mapsapi&chl=pin%27i%5Chv%27a%5C]h%5C]o%5Cffee58%27fC%5CLauto%27f%5C&ext=.png" class="img-fluid" alt="Yellow Pin">
                @endif
                {{ __($symptom->name) }}
              </label>
            </div>
          @endforeach

          <div class="custom-control custom-switch mt-2">
            <input type="checkbox" class="custom-control-input" id="greenMarkerSwitch" checked onchange="greenMarkerSwitch(this.checked)">
            <label class="custom-control-label" for="greenMarkerSwitch">
              <img src="https://chart.apis.google.com/chart?cht=d&chdp=mapsapi&chl=pin%27i%5Chv%27a%5C]h%5C]o%5C4caf50%27fC%5CLauto%27f%5C&ext=.png" class="img-fluid" alt="Green Pin">
              {{ __('No symptoms') }}
            </label>
          </div>

          <div class="custom-control custom-switch mt-2">
            <input type="checkbox" class="custom-control-input" id="heatMapSwitch" onchange="heatMapSwitch(this.checked)">
            <label class="custom-control-label" for="heatMapSwitch">
              {{ __('Heatmap') }}
            </label>
          </div>

          <div class="custom-control custom-switch mt-2">
            <input type="checkbox" class="custom-control-input" id="markerClusterSwitch" onchange="markerClusterSwitch(this.checked)">
            <label class="custom-control-label" for="markerClusterSwitch">
              {{ __('Cluster markers') }}
            </label>
          </div>

          <div class="form-group row mt-2 mb-0">
            <label for="inputDateFrom" class="col-sm-3 col-form-label">From</label>
            <div class="col-sm-9">
              <input type="date" class="form-control" id="inputDateFrom" onchange="refreshDate()">
            </div>
          </div>

          <div class="form-group row mt-2 mb-0">
            <label for="inputDateTo" class="col-sm-3 col-form-label">To</label>
            <div class="col-sm-9">
              <input type="date" class="form-control" id="inputDateTo" onchange="refreshDate()">
            </div>
          </div>

        </card-basic>
      </div>

    </div>

  </div>
@endsection

@section('scripts')
  <script type="text/javascript" src="{{ asset('js/map.js') }}" defer></script>
  <script type="text/javascript" defer>
    // gets all reports from api
    getDataFromAPI = async (url) => {
      const baseURL = window.location.origin;
      const response = await fetch(baseURL + url);
      const json = await response.json();
      return json.data;
    }

    doesMapExist = () => {
      if (document.getElementById("map")) {
        initMap();
      }
      else {
        // TODO: sometimes the google maps api will call initMap() when 'map' hasn't loaded yet and it returns an error
        setTimeout(function () {
          doesMapExist();
        }, 1000);
      }
    }
  </script>
  <script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config('settings.google_maps_api') }}&libraries=visualization&callback=doesMapExist"></script>
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
      )))
      @slot('current_page', 'Profile')
    @endcomponent

    
    {{-- Update Password --}}
    <card-basic title="Update Password" class="mt-4">
        <form method="POST" action="{{ route('admin.profile.password.update') }}">
            @csrf
            <div class="form-group">
                <label for="inputCurrentPassword" class="bmd-label-floating">Current Password</label>
                <input type="password" class="form-control" id="inputCurrentPassword" name="current" required>
            </div>
            <div class="form-group">
                <label for="inputNewPassword" class="bmd-label-floating">New Password</label>
                <input type="password" class="form-control" id="inputNewPassword" name="new" required>
            </div>
            <div class="form-group">
                <label for="inputNewPasswordConfirmation" class="bmd-label-floating">Confirm New Password</label>
                <input type="password" class="form-control" id="inputNewPasswordConfirmation" name="confirm" required>
            </div>
            <button-submit text="Update" icon="edit" class="float-right" />
        </form>
    </card-basic>
  </div>
@endsection