routes/web.php
<?php

use App\Symptom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang', 'PageController@locale')->name('locale');
Route::get('lang/{locale}', 'PageController@setLocale');

// Pages
Route::get('', 'PageController@survey')->name('survey');
Route::post('', 'ReportController@store')->name('survey.store');
Route::get('thank-you', 'PageController@thanks')->name('thanks');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('map', 'PageController@map')->name('map');
Route::get('privacy', 'PageController@privacy')->name('privacy');
Route::get('about-us', 'PageController@aboutUs')->name('about-us');

// Biñan
Route::get('biñan', 'PageController@biñan')->name('biñan');
Route::get('binan', 'RedirectController@biñan');

// Auth
Auth::routes(['register' => false]);
Route::get('password/{token}', 'PasswordController@createPassword')->name('password-create');
Route::post('password/create', 'PasswordController@storePassword')->name('password-store');
// Route::get('verify/{token}', 'AdminController@verifyEmail');

Route::prefix('admin')->name('admin.')->group(function () {

    // Main admin page
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('map', 'AdminPageController@map')->name('map');

    Route::get('cases', 'AdminPageController@cases')->name('cases');

    // Resources
    Route::get('reports/problems', 'ReportController@problems')->name('reports.problems');
    Route::resource('reports', 'ReportController');
    Route::post('reports/{report}/flag', 'ReportController@flag')->name('reports.flag');
    Route::post('reports/{report}/fake', 'ReportController@fake')->name('reports.fake');
    Route::post('reports/{report}/unflag', 'ReportController@unflag')->name('reports.unflag');
    Route::post('reports/{report}/unfake', 'ReportController@unfake')->name('reports.unfake');
    Route::resource('users', 'UserController');

    Route::resource('symptoms', 'SymptomController');
    Route::get('symptoms/{symptom}/image/edit', 'SymptomController@imageEdit')->name('symptoms.image.edit');
    Route::put('symptoms/{symptom}/image/update', 'SymptomController@imageUpdate')->name('symptoms.image.update');
    Route::post('symptoms/image/none/update', 'SymptomController@noneImageUpdate')->name('symptoms.image.none.update');

    Route::resource('case-statuses', 'CaseStatusController');
    Route::put('case-statuses/{case_status}/activate', 'CaseStatusController@activate')->name('case-statuses.activate');
    Route::put('case-statuses/{case_status}/deactivate', 'CaseStatusController@deactivate')->name('case-statuses.deactivate');

    Route::resource('regions', 'RegionController');
    Route::resource('provinces', 'ProvinceController');
    Route::resource('cities', 'CityController');
    Route::resource('barangays', 'BarangayController');
    Route::resource('barangay-cases', 'BarangayCaseController');

    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/password/update', 'ProfileController@updatePassword')->name('profile.password.update');
});

Route::get('{url}', function (string $url) {
    return redirect(route('survey'));
});

app/Barangay.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Barangay extends Model
{
    use SoftDeletes;

    public function city()
    {
        return $this->belongsTo('App\City');
    }

    public function cases()
    {
        return $this->hasMany('App\BarangayCase');
    }
}

app/Http/Controllers/BarangayController.php
<?php

namespace App\Http\Controllers;

use App\Barangay;
use App\CaseStatus;
use App\City;
use Illuminate\Http\Request;

class BarangayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $barangays = Barangay::all();
        $cities = City::all();
        $caseStatuses = CaseStatus::all();

        return view('admin.barangays.index', compact('barangays', 'cities', 'caseStatuses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'string|required|max:191',
            'city' => 'integer|required|max:191',
            'lat' => 'string|required|max:100',
            'lng' => 'string|required|max:100',
        ]);

        // Only accept valid coordinates
        if (abs(request('lat')) > 90 || abs(request('lng') > 180)) {
            return back();
        }

        $barangay = new Barangay();

        if (!City::find(request('city'))) {
            return back()->with('warning', 'Invalid city ID.');
        }

        $barangay->city_id = request('city');
        $barangay->name = request('name');
        $barangay->lat = request('lat');
        $barangay->lng = request('lng');

        if ($barangay->save()) {
            return back()->with('success', 'Added new barangay.');
        }
        return back()->with('danger', 'Erorr adding new barangay.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Barangay  $barangay
     * @return \Illuminate\Http\Response
     */
    public function show(Barangay $barangay)
    {
        $caseStatuses = CaseStatus::all();

        return view('admin.barangays.show', compact('barangay', 'caseStatuses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Barangay  $barangay
     * @return \Illuminate\Http\Response
     */
    public function edit(Barangay $barangay)
    {
        $cities = City::all();

        return view('admin.barangays.edit', compact('barangay', 'cities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Barangay  $barangay
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Barangay $barangay)
    {
        $validatedData = $request->validate([
            'name' => 'string|required|max:191',
            'city' => 'integer|required|max:191',
            'lat' => 'string|required|max:100',
            'lng' => 'string|required|max:100',
        ]);

        // Only accept valid coordinates
        if (abs(request('lat')) > 90 || abs(request('lng') > 180)) {
            return back();
        }

        if (!City::find(request('city'))) {
            return back()->with('warning', 'Invalid city ID.');
        }

        $barangay->city_id = request('city');
        $barangay->name = request('name');
        $barangay->lat = request('lat');
        $barangay->lng = request('lng');

        if ($barangay->save()) {
            return back()->with('success', 'Updated barangay.');
        }
        return back()->with('danger', 'Erorr updating barangay.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Barangay  $barangay
     * @return \Illuminate\Http\Response
     */
    public function destroy(Barangay $barangay)
    {
        if ($barangay->delete()) {
            return back()->with('success', 'Deleted barangay');
        }
        return back()->with('danger', 'Error deleting barangay.');
    }
}

resources/views/admin/barangays/edit.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
        array('Regions', route('admin.regions.index')),
        array($barangay->city->province->region->name, route('admin.regions.show', ['region' => $barangay->city->province->region->id])),
        array('Provinces', route('admin.provinces.index')),
        array($barangay->city->province->name, route('admin.provinces.show', ['province' => $barangay->city->province->id])),
        array('Cities', route('admin.cities.index')),
        array($barangay->city->name, route('admin.cities.show', ['city' => $barangay->city->id])),
        array('Barangays', route('admin.barangays.index')),
        array($barangay->name, route('admin.barangays.show', ['barangay' => $barangay->id])),
      )))
      @slot('current_page', 'Edit')
    @endcomponent

    <card-basic title="Update Barangay" class="mt-4">
      @include('components.errors')
      <form action="{{ route('admin.barangays.update', ['barangay' => $barangay->id]) }}" method="POST">
        @method('PUT')
        @csrf

        <div class="alert alert-warning" role="alert">
          If the city you want isn't showing up in the choices below, add that city first in the database. Go <a href="{{ route('admin.cities.index') }}">here</a>.
        </div>

        <div class="form-group">
          <label for="inputCity" class="m-0">City</label>
          <select class="form-control" id="inputCity" name="city">
            @foreach($cities as $city)
              @if($city->id == $barangay->city_id)
                <option value="{{ $city->id }}" selected>{{ $city->name }}</option>
              @else
                <option value="{{ $city->id }}">{{ $city->name }}</option>
              @endif
            @endforeach
          </select>
        </div>

        <div class="form-group">
          <label for="inputName">Barangay Name</label>
          <input type="text" class="form-control" id="inputName" name="name" required value="{{ $barangay->name }}">
        </div>

        <div class="form-group">
          <label for="inputLat">Latitude</label>
          <input type="text" class="form-control" id="inputLat" name="lat" required value="{{ $barangay->lat }}">
        </div>

        <div class="form-group">
          <label for="inputLng">Longitude</label>
          <input type="text" class="form-control" id="inputLng" name="lng" required value="{{ $barangay->lng }}">
        </div>

        <button-submit class="float-right"/>
      </form>
    </card-basic>

  </div>
@endsection

resources/views/admin/barangays/index.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
        array('Regions', route('admin.regions.index')),
        array('Provinces', route('admin.provinces.index')),
        array('Cities', route('admin.cities.index')),
      )))
      @slot('current_page', 'Barangays')
    @endcomponent

    <card-basic title="Map" class="mt-4">
      <template v-slot:image>
        <div id="map" class="w-100" style="height: 512px;"></div>
      </template>
    </card-basic>

    @component('components.cards.barangay-create')
      @slot('cities', $cities)
    @endcomponent

    @component('components.cards.barangays')
      @slot('barangays', $barangays)
    @endcomponent

    @foreach($barangays as $barangay)
      @component('components.cards.barangay-cases-dates')
        @slot('caseStatuses', $caseStatuses)
        @slot('barangay', $barangay)
      @endcomponent
    @endforeach

  </div>
@endsection

@section('scripts')
  <script>

    var markers = [];

    initMap = () => {

        // fetch reports
        getDataFromAPI('/api/barangays/').then(barangays => {

            const mapSettings = {
                // view of the philippines
                center: {
                    lat: 11,
                    lng: 123
                },
                zoom: 5,
                // disable satellite view
                mapTypeControl: false,
                // disable street view
                streetViewControl: false,
                styles: [{
                    "featureType": "administrative",
                    "elementType": "geometry",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "administrative.land_parcel",
                    "elementType": "labels",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "landscape.man_made",
                    "elementType": "geometry",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "poi",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "poi",
                    "elementType": "labels.text",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "road",
                    "elementType": "labels.icon",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "road.local",
                    "elementType": "labels",
                    "stylers": [{
                        "visibility": "off"
                    }]
                },
                {
                    "featureType": "transit",
                    "stylers": [{
                        "visibility": "off"
                    }]
                }
                ],
            };

            // map
            map = new google.maps.Map(document.getElementById('map'), mapSettings);

            // for each report
            barangays.forEach(barangay => {

                // check if coordinates exist
                if (barangay.lat != null && barangay.lng != null) {

                    var location = {
                        lat: parseFloat(barangay.lat),
                        lng: parseFloat(barangay.lng)
                    };

                    // default icon is green
                    var pinColor = '4caf50';
                    var color = 'green';

                    var icon = {
                        url: 'https://chart.apis.google.com/chart?chst=d_map_pin_letter&chld= |' + pinColor,
                        size: new google.maps.Size(21, 34),
                        origin: new google.maps.Point(0, 0),
                        anchor: new google.maps.Point(4, 19),
                        scaledSize: new google.maps.Size(11, 20) // scaled size
                    }

                    var infowindow = new google.maps.InfoWindow({
                      content: barangay.name
                    });

                    var marker = new google.maps.Marker({
                        position: location,
                        map: map,
                        icon: icon,
                        color: color,
                    });
                    marker.addListener('click', function() {
                      infowindow.open(map, marker);
                    });
                    markers.push(marker);

                }
            });

            var options = {};

            markerCluster = new MarkerClusterer(null, markers, options);

            heatMapLayer = new google.maps.visualization.HeatmapLayer({
                data: heatMapData,
                map: map,
                dissipating: false,
                radius: 0.0075 * map.getZoom(),
                maxIntensity: 360,
            });

        });
    }
  </script>
  <script type="text/javascript" defer>
    // gets all reports from api
    getDataFromAPI = async (url) => {
      const baseURL = window.location.origin;
      const response = await fetch(baseURL + url);
      const json = await response.json();
      return json.data;
    }

    doesMapExist = () => {
      if (document.getElementById("map")) {
        initMap();
      }
      else {
        // TODO: sometimes the google maps api will call initMap() when 'map' hasn't loaded yet and it returns an error
        setTimeout(function () {
          doesMapExist();
        }, 1000);
      }
    }
  </script>
  <script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config('settings.google_maps_api') }}&libraries=visualization&callback=doesMapExist"></script>
@endsection

resources/views/admin/barangays/show.blade.php
@extends('layouts.admin.index')

@section('content')
  <div class="container">

    @component('components.breadcrumb')
      @slot('pages', array(
        array('Dashboard', route('admin.dashboard')),
        array($barangay->city->province->region->name, route('admin.regions.show', ['region' => $barangay->city->province->region->id])),
        array($barangay->city->province->name, route('admin.provinces.show', ['province' => $barangay->city->province->id])),
        array($barangay->city->name, route('admin.cities.show', ['city' => $barangay->city->id])),
      )))
      @slot('current_page', $barangay->name)
    @endcomponent

    <card-basic title="{{ $barangay->name }}" class="mt-4">
      <template v-slot:options>
        <options-dropdown>
          <a class="dropdown-item" href="{{ route('admin.barangays.edit', ['barangay' => $barangay->id]) }}">
            Edit
          </a>
          <button class="dropdown-item text-danger" data-toggle="modal" data-target="#deleteConfirmationModal"
            data-action="{{ route('admin.barangays.destroy', ['barangay' => $barangay->id]) }}">
            Delete
          </button>
        </options-dropdown>
      </template>
      <template v-slot:image>
        <div class="table-responsive">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Latitude</th>
                <td>{{ $barangay->lat }}</td>
              </tr>
              <tr>
                <th>Longitude</th>
                <td>{{ $barangay->lng }}</td>
              </tr>
              <tr>
                <th>City</th>
                <td>
                  <a href="{{ route('admin.cities.show', ['city' => $barangay->city->id]) }}">
                    {{ $barangay->city->name }}
                  </a>
                </td>
              </tr>
              <tr>
                <th>Province</th>
                <td>
                  <a href="{{ route('admin.provinces.show', ['province' => $barangay->city->province->id]) }}">
                    {{ $barangay->city->province->name }}
                  </a>
                </td>
              </tr>
              <tr>
                <th>Region</th>
                <td>
                  <a href="{{ route('admin.regions.show', ['region' => $barangay->city->province->region->id]) }}">
                    {{ $barangay->city->province->region->name }}
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </tr>
      </template>
    </card-basic>

    <card-basic title="Add Case Summary" class="mt-4">
      @include('components.errors')
      <form action="{{ route('admin.barangay-cases.store') }}" method="POST">
        @csrf

        <input type="text" name="barangay" value="{{ $barangay->id }}" readonly hidden>

        <div class="row">

          @foreach($caseStatuses as $caseStatus)
            @if(!isset($caseStatus->deactivated_at))
              <div class="col-md-3">
                <div class="form-group">
                  <label for="inputCaseStatus{{ $caseStatus->id }}">{{ $caseStatus->name }}</label>
                  <input type="number" class="form-control" id="inputCaseStatus{{ $caseStatus->id }}" name="case_statuses[{{ $caseStatus->id }}]">
                </div>
              </div>
            @endif
          @endforeach

        </div>

        <div class="form-group">
          <label for="inputDate">Date</label>
          <input type="date" class="form-control" id="inputDate" name="date" value="{{ date('Y-m-d') }}" required>
        </div>

        <button-submit class="float-right"/>
      </form>
    </card-basic>

    @component('components.cards.barangay-cases-dates')
      @slot('caseStatuses', $caseStatuses)
      @slot('barangay', $barangay)
    @endcomponent

  </div>
@endsection