routes/web.php
<?php

use App\Symptom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang', 'PageController@locale')->name('locale');
Route::get('lang/{locale}', 'PageController@setLocale');

// Pages
Route::get('', 'PageController@survey')->name('survey');
Route::post('', 'ReportController@store')->name('survey.store');
Route::get('thank-you', 'PageController@thanks')->name('thanks');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('map', 'PageController@map')->name('map');
Route::get('privacy', 'PageController@privacy')->name('privacy');
Route::get('about-us', 'PageController@aboutUs')->name('about-us');

// Biñan
Route::get('biñan', 'PageController@biñan')->name('biñan');
Route::get('binan', 'RedirectController@biñan');

// Auth
Auth::routes(['register' => false]);
Route::get('password/{token}', 'PasswordController@createPassword')->name('password-create');
Route::post('password/create', 'PasswordController@storePassword')->name('password-store');
// Route::get('verify/{token}', 'AdminController@verifyEmail');

Route::prefix('admin')->name('admin.')->group(function () {

    // Main admin page
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('map', 'AdminPageController@map')->name('map');

    Route::get('cases', 'AdminPageController@cases')->name('cases');

    // Resources
    Route::get('reports/problems', 'ReportController@problems')->name('reports.problems');
    Route::resource('reports', 'ReportController');
    Route::post('reports/{report}/flag', 'ReportController@flag')->name('reports.flag');
    Route::post('reports/{report}/fake', 'ReportController@fake')->name('reports.fake');
    Route::post('reports/{report}/unflag', 'ReportController@unflag')->name('reports.unflag');
    Route::post('reports/{report}/unfake', 'ReportController@unfake')->name('reports.unfake');
    Route::resource('users', 'UserController');

    Route::resource('symptoms', 'SymptomController');
    Route::get('symptoms/{symptom}/image/edit', 'SymptomController@imageEdit')->name('symptoms.image.edit');
    Route::put('symptoms/{symptom}/image/update', 'SymptomController@imageUpdate')->name('symptoms.image.update');
    Route::post('symptoms/image/none/update', 'SymptomController@noneImageUpdate')->name('symptoms.image.none.update');

    Route::resource('case-statuses', 'CaseStatusController');
    Route::put('case-statuses/{case_status}/activate', 'CaseStatusController@activate')->name('case-statuses.activate');
    Route::put('case-statuses/{case_status}/deactivate', 'CaseStatusController@deactivate')->name('case-statuses.deactivate');

    Route::resource('regions', 'RegionController');
    Route::resource('provinces', 'ProvinceController');
    Route::resource('cities', 'CityController');
    Route::resource('barangays', 'BarangayController');
    Route::resource('barangay-cases', 'BarangayCaseController');

    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/password/update', 'ProfileController@updatePassword')->name('profile.password.update');
});

Route::get('{url}', function (string $url) {
    return redirect(route('survey'));
});

resources/views/layouts/admin/drawer.blade.php
<div class="bmd-layout-container bmd-drawer-f-l bmd-drawer-overlay">
  <header class="bmd-layout-header bg-dark">
    <div class="navbar navbar-light bg-faded">
      <button class="navbar-toggler" type="button" data-toggle="drawer" data-target="#dw-s2">
        <span class="sr-only">Toggle drawer</span>
        <i class="material-icons text-white">menu</i>
      </button>
      <ul class="nav navbar-nav">
        <li class="nav-item text-white">{{ config('app.name', 'SymptomTracker') }}</li>
      </ul>
      <ul class="nav navbar-nav invisible">
        <li class="nav-item text-white">{{ config('app.name', 'SymptomTracker') }}</li>
      </ul>
    </div>
  </header>
  <div id="dw-s2" class="bmd-layout-drawer bg-faded vh-100">
    <header class="bg-dark">
      <a class="navbar-brand text-white">{{ config('app.name', 'SymptomTracker') }}</a>
    </header>
    <ul class="list-group">
      <a href="{{ route('admin.dashboard') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">home</i>
        Dashboard
      </a>
      <a href="{{ route('admin.profile') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">account_circle</i>
        Profile
      </a>
      <a href="{{ route('admin.map') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">map</i>
        Map
      </a>
      <a href="{{ route('admin.users.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">people</i>
        Users
      </a>
      <a href="{{ route('admin.symptoms.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">people</i>
        Symptoms
      </a>
      <a href="{{ route('admin.cases') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">import_contacts</i>
        Cases
      </a>
      <a href="{{ route('admin.case-statuses.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">import_contacts</i>
        Case Statuses
      </a>
      <a href="{{ route('admin.regions.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">account_balance</i>
        Regions
      </a>
      <a href="{{ route('admin.provinces.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">account_balance</i>
        Provinces
      </a>
      <a href="{{ route('admin.cities.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">account_balance</i>
        Cities
      </a>
      <a href="{{ route('admin.barangays.index') }}" class="list-group-item">
        <i class="material-icons material-icons-outlined mr-4">account_balance</i>
        Barangays
      </a>
      <a class="list-group-item" href="{{ route('logout') }}"
        onclick="event.preventDefault();document.getElementById('logout-form').submit();">
        <i class="material-icons material-icons-outlined mr-4">exit_to_app</i>
        Logout
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
      </form>
    </ul>
  </div>

  <main class="bmd-layout-content h-100">
    @include('components.alerts')
    @yield('content')
    <footer class="mt-4">
      <div class="text-center text-muted row py-4">
        <span class="mx-auto">
          &copy; {{ now()->year }} {{ config('app.name', 'SymptomTracker') }}
        </span>
      </div>
    </footer>
  </main>

</div>

resources/views/layouts/admin/index.blade.php
<!doctype html>
<html class="h-100" lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

  @include('components.google-analytics')

  {{-- CSRF Token --}}
  <meta name="csrf-token" content="{{ csrf_token() }}">

  {{-- Meta data tags --}}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1, user-scalable=0">

  {{-- For Admin Pages --}}
  <meta name="robots" content="noindex, nofollow" />

  {{-- Title --}}
  <title>{{ config('app.name', 'Survey Tracker') }}</title>

  @include('components.icons')

  {{-- Material Bootstrap CSS --}}
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

  {{-- Material Icons --}}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  {{-- JQuery UI --}}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  {{-- CSS --}}
  <link href="{{ asset('css/app-md.css') }}" rel="stylesheet">

  @yield('styles')

</head>

<body class="h-100">

  <div id="app" class="h-100">
    @include('components.modals.delete-confirmation')
    @include('components.modals.confirmation')
    @include('layouts.admin.drawer')
  </div>

  @include('layouts.admin.javascript')

</body>

</html>

resources/views/layouts/admin/javascript.blade.php
{{-- JavaScript --}}

{{-- JQuery --}}
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

{{-- Popper --}}
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
  integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>

{{-- Slider --}}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{{-- Moment JS --}}
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

{{-- Date Range Picker --}}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

{{-- Bootstrap Material Design --}}
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

{{-- Custom Javascript --}}
<script src="{{ asset('js/app-md.js') }}" defer></script>
<script src="{{ asset('js/vue.js') }}" defer></script>
<script src="{{ asset('js/modal-functions.js') }}" defer></script>

<script>
  $(document).ready(function() {
    $('body').bootstrapMaterialDesign();
  });
</script>

@yield('scripts')